// src/test/recordRconFixtures.ts
//
// Manual CLI: drives a real `RconProtocol` through the canonical conversation
// script (fixtures/rconScript.ts) against a *live* Minecraft server, tees the
// wire bytes through a `RecordingSocket`, and writes the result out as a
// checked-in fixture module the replay suite (rconProtocol.test.ts) can run
// against offline forever after.
//
// Not part of `npm test` — it needs real server credentials and produces a
// file you should review (and commit) by hand. Run it with:
//
//   npm run compile
//   node out/test/recordRconFixtures.js <host> <port> <password> [fixtureName]
//
// Re-run it whenever you want to refresh the recorded conversation against
// what a real server actually does today (new MC version, different
// fragmentation behavior, changed `help` output, etc) — that's the entire
// point of recording instead of hand-authoring (compare synthetic.ts, which
// only encodes our *assumptions* about the protocol).

import * as fs from 'fs';
import * as path from 'path';
import type { Logger } from '../logger';
import { RconProtocol } from '../rconProtocol';
import { RecordingSocket } from './support/recordingSocket';
import { RconFrame, encodeFrames } from './support/fakeSocket';
import { RconPacketType, encodeRconPacket } from './support/rconWireFormat';
import { RCON_CONVERSATION_SCRIPT } from './fixtures/rcon/script';

// The recorded conversation's first outgoing packet is always the real
// password, base64-encoded but trivially recoverable — not something to
// commit to git. `RconProtocol.authenticate()` is always the very first thing
// written (request id 1, type AUTH), so we know exactly which frame to swap;
// replacing it with a freshly-built packet using this placeholder keeps the
// bytes self-consistent as long as the replay test authenticates with the
// same placeholder (the generated fixture module exports it for that reason).
const FIXTURE_PASSWORD_PLACEHOLDER = 'fixture-password';

function redactPassword(frames: readonly RconFrame[]): RconFrame[] {
  const [authFrame, ...rest] = frames;
  if (!authFrame || authFrame.direction !== 'sent') {
    throw new Error('Expected the first recorded frame to be the outgoing AUTH packet — got something else. Refusing to write a fixture that might still contain the real password.');
  }
  return [
    { direction: 'sent', data: encodeRconPacket(1, RconPacketType.AUTH, FIXTURE_PASSWORD_PLACEHOLDER) },
    ...rest,
  ];
}

function consoleLogger(): Logger {
  return {
    info: (message) => console.log(`[info] ${message}`),
    warning: (message) => console.warn(`[warning] ${message}`),
    error: (message) => console.error(`[error] ${message}`),
    debug: (message) => console.debug(`[debug] ${message}`),
  };
}

function renderFixtureModule(args: {
  recordedAt: string;
  encodedFrames: ReturnType<typeof encodeFrames>;
  expectedResponses: string[];
}): string {
  return `// AUTO-GENERATED by \`npm run record-rcon-fixtures\` against a live server on ${args.recordedAt}.
// Do not hand-edit — re-run the recorder (see recordRconFixtures.ts) to refresh.
//
// Neither the server's address nor its password were recorded — this repo is
// public, and checking either in would mean publishing where your Minecraft
// server lives. The auth packet's body has been replaced with the placeholder
// below (byte-identical in shape, just with a different password), and the
// replay test authenticates with the same placeholder so the conversation
// still lines up byte-for-byte. The host/port RconProtocol is constructed
// with during replay are themselves placeholders — the wire conversation
// doesn't depend on them at all.

import { RconFixture, EncodedFrame, decodeFrames } from '../../support/fakeSocket';

export const password = '${FIXTURE_PASSWORD_PLACEHOLDER}';

const encodedFrames: EncodedFrame[] = ${JSON.stringify(args.encodedFrames, null, 2)};

export const fixture: RconFixture = {
  description: 'Recorded against a live server on ${args.recordedAt}.',
  frames: decodeFrames(encodedFrames),
  expectedResponses: ${JSON.stringify(args.expectedResponses, null, 2)},
};
`;
}

async function main(): Promise<void> {
  const [host, portArg, password, fixtureName] = process.argv.slice(2);
  if (!host || !portArg || !password) {
    console.error('Usage: node out/test/recordRconFixtures.js <host> <port> <password> [fixtureName]');
    process.exitCode = 1;
    return;
  }
  const port = Number(portArg);
  const name = fixtureName || 'recorded';

  const logger = consoleLogger();
  const socket = new RecordingSocket();
  const protocol = new RconProtocol(host, port, password, logger, () => socket);

  const expectedResponses: string[] = [];
  try {
    logger.info(`Connecting to ${host}:${port}...`);
    await protocol.connect();

    for (const command of RCON_CONVERSATION_SCRIPT) {
      logger.info(`Sending: ${command}`);
      const response = await protocol.send(command);
      expectedResponses.push(response ?? '');
      logger.info(`Received ${(response ?? '').length} bytes`);
    }
  } finally {
    await protocol.disconnect();
  }

  // __dirname is out/test at runtime — fixtures are authored in src and compiled alongside everything else
  const outputPath = path.join(__dirname, '..', '..', 'src', 'test', 'fixtures', 'rcon', `${name}.ts`);
  const moduleSource = renderFixtureModule({
    recordedAt: new Date().toISOString(),
    encodedFrames: encodeFrames(redactPassword(socket.frames)),
    expectedResponses,
  });
  fs.writeFileSync(outputPath, moduleSource, 'utf8');
  logger.info(`Wrote fixture to ${outputPath} — review it, then commit it alongside this run's test results.`);
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
